build:
    image: klakegg/hugo:0.68.3
    volumes:
        - ".:/src"
        - "./public:/target"
server:
    image: klakegg/hugo:0.68.3
    command: server
    volumes:
        - ".:/src"
    ports:
        - "1313:1313"